/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author Elizabeth
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btningresar = new javax.swing.JButton();
        Text_Usuario = new javax.swing.JLabel();
        Text_Contrasenia = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        txtusuario = new javax.swing.JTextField();
        login_icon = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btningresar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btningresar.setText("Ingresar");
        btningresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btningresarMouseClicked(evt);
            }
        });
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });
        jPanel1.add(btningresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));

        Text_Usuario.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        Text_Usuario.setText("Usuario:");
        jPanel1.add(Text_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        Text_Contrasenia.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        Text_Contrasenia.setText("Contraseña:");
        jPanel1.add(Text_Contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        Password.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        Password.setText("jPasswordField1");
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 200, 50));

        txtusuario.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 200, 40));

        login_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imagenes/login_icon.png"))); // NOI18N
        jPanel1.add(login_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imagenes/Pantallas.png"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        //
    }//GEN-LAST:event_btningresarActionPerformed

    private void btningresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btningresarMouseClicked
        String Usuario = "Admin";
        String Contraseña =  "Mayra";
                
        String Pass = new String (Password.getPassword());
        if(txtusuario.getText().equals(Usuario)&& Pass.equals(Contraseña)){
            Menu menu=new Menu();
            menu.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Usaurio / Contraseña Incorrecta");
        }

        
        
        


    }//GEN-LAST:event_btningresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Text_Contrasenia;
    private javax.swing.JLabel Text_Usuario;
    private javax.swing.JButton btningresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel login_icon;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
