/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.util.Calendar;
import java.util.GregorianCalendar;
import proyecto.inventariosBL.InventarioBL;
import proyecto.inventariosDAL.Conexion;
import proyecto.ventasBL.VentasBL;
/**
 *
 * @author Elizabeth
 */
public class Ventas extends javax.swing.JFrame {

    Calendar fecha_actual=new GregorianCalendar();
    
    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
        jdFecha_actual.setCalendar(fecha_actual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Text_Ventas = new javax.swing.JLabel();
        Text_Vendedor = new javax.swing.JLabel();
        Text_Cliente = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcategoria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtpiezas = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        btnok = new javax.swing.JButton();
        txtvendedor = new javax.swing.JTextField();
        txtcliente = new javax.swing.JTextField();
        Text_Subtotal = new javax.swing.JLabel();
        Text_Descuento = new javax.swing.JLabel();
        btncompra = new javax.swing.JButton();
        txtnuevo = new javax.swing.JButton();
        Text_Total = new javax.swing.JLabel();
        txtsub = new javax.swing.JTextField();
        txtdescuento = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        Background = new javax.swing.JLabel();
        jdFecha_actual = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text_Ventas.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 60)); // NOI18N
        Text_Ventas.setText("VENTAS");
        jPanel1.add(Text_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        Text_Vendedor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        Text_Vendedor.setText("Vendedor:");
        jPanel1.add(Text_Vendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        Text_Cliente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        Text_Cliente.setText("Cliente:");
        jPanel1.add(Text_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prenda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 0, 36), new java.awt.Color(153, 0, 204))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel4.setText("Código:");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel5.setText("Precio:");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel6.setText("Categoría:");

        txtcategoria.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        txtcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Blusa", "Top", "Pantalón", "Jeans", "Chaqueta", "Chamarra", "Playera", "Sudadera" }));
        txtcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcategoriaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel3.setText("Piezas:");

        txtcodigo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N

        txtpiezas.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N

        txtprecio.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N

        btnok.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btnok.setText("Ok");
        btnok.setToolTipText("En base a las Piezas y el Precio genera un subtotal.");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(btnok)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnok))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtpiezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 410, 270));

        txtvendedor.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jPanel1.add(txtvendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, 40));

        txtcliente.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jPanel1.add(txtcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 170, 40));

        Text_Subtotal.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        Text_Subtotal.setText("Subtotal:");
        jPanel1.add(Text_Subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, -1, -1));

        Text_Descuento.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        Text_Descuento.setText("Descuento %");
        jPanel1.add(Text_Descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        btncompra.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btncompra.setText("Finalizar Compra");
        btncompra.setToolTipText("Calcula (Automaticamente) el Total, en base al Subtotal calculado y el % de Descuento Ingresado.");
        btncompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncompraActionPerformed(evt);
            }
        });
        jPanel1.add(btncompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, -1, -1));

        txtnuevo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        txtnuevo.setText("Nuevo/Limpiar");
        txtnuevo.setToolTipText("Limpia todos los datos ingresados de la compra. (Desde Vendedor,Clientes Datos de Prensa y los calculos para el Total)");
        txtnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnuevoActionPerformed(evt);
            }
        });
        jPanel1.add(txtnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, -1, -1));

        Text_Total.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        Text_Total.setText("Total:");
        jPanel1.add(Text_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));

        txtsub.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jPanel1.add(txtsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 130, 40));

        txtdescuento.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        txtdescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescuentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtdescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 120, 40));

        txttotal.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jPanel1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 140, 40));

        btnGuardar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 110, 40));

        Background.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imagenes/FondoSinTransparencia.png"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jdFecha_actual.setBackground(new java.awt.Color(135, 133, 207));
        jdFecha_actual.setForeground(new java.awt.Color(135, 133, 207));
        jdFecha_actual.setDateFormatString("dd-MMM-yy");
        jdFecha_actual.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jPanel1.add(jdFecha_actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 150, 40));

        jMenu1.setText("Inicio");
        jMenu1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Inventario");
        jMenu2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Salir");
        jMenu3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        Menu menu=new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        Inventario inventario=new Inventario();
        inventario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void txtnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnuevoActionPerformed
        txtvendedor.setText("");
        txtcliente.setText("");
        txtcodigo.setText("");
        txtpiezas.setText("");
        txtprecio.setText("");
        txtsub.setText("");
        txtdescuento.setText("");
        txttotal.setText("");
    }//GEN-LAST:event_txtnuevoActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        float pi,p,sub;
        pi=Float.parseFloat(txtpiezas.getText());
        p=Float.parseFloat(txtprecio.getText());
        sub=pi*p;
        txtsub.setText(String.valueOf(sub));
    }//GEN-LAST:event_btnokActionPerformed

    private void btncompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncompraActionPerformed
        float descuento,total,sub;
        sub=Float.parseFloat(txtsub.getText());
        descuento=Float.parseFloat(txtdescuento.getText());
        total=sub-(sub*(descuento/100));
        txttotal.setText(String.valueOf(total));
        
        
    }//GEN-LAST:event_btncompraActionPerformed

    private void txtdescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescuentoActionPerformed

    private void txtcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcategoriaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

Conexion conexion = new Conexion();
VentasBL ventas = recuperarDatosGUI();
String strSentenciaInsert=String.format("INSERT INTO Ventas (vendedorNombre, clienteNombre, codigo, "
        + "categoria, piezas, precio, subtotal, descuento, total)\n" +
"VALUES('%s', '%s', %d, '%s', %d, %f, %f, %f, %f)", ventas.getVendedorNombre(),ventas.getClienteNombre(),ventas.getCodigo(),
ventas.getCategoria(),ventas.getPiezas(),ventas.getPrecio(),ventas.getSubtotal(),ventas.getDescuento(),
ventas.getTotal());

conexion.ejecutarSentenciaSQL(strSentenciaInsert);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    
    public VentasBL recuperarDatosGUI(){
        VentasBL oVentas = new VentasBL();
        int codigo =(txtcodigo.getText().isEmpty())?0:Integer.parseInt(txtcodigo.getText());
        int piezas =(txtpiezas.getText().isEmpty())?0:Integer.parseInt(txtpiezas.getText());
        int precio=(txtprecio.getText().isEmpty())?0:Integer.parseInt(txtprecio.getText());
        double subTot=(txtsub.getText().isEmpty())?0:Double.parseDouble(txtsub.getText());
        int desc=(txtdescuento.getText().isEmpty())?0:Integer.parseInt(txtdescuento.getText());
        double tot=(txttotal.getText().isEmpty())?0:Double.parseDouble(txttotal.getText());
        oVentas.setVendedorNombre(txtvendedor.getText());
        oVentas.setClienteNombre(txtcliente.getText());
        oVentas.setCodigo(codigo);
        oVentas.setCategoria(txtcategoria.getSelectedItem().toString());
        oVentas.setPiezas(piezas);
        oVentas.setPrecio(precio);
        oVentas.setSubtotal(subTot);
        oVentas.setDescuento(desc);
        oVentas.setTotal(tot);
        
        
        
        return oVentas;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Text_Cliente;
    private javax.swing.JLabel Text_Descuento;
    private javax.swing.JLabel Text_Subtotal;
    private javax.swing.JLabel Text_Total;
    private javax.swing.JLabel Text_Vendedor;
    private javax.swing.JLabel Text_Ventas;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btncompra;
    private javax.swing.JButton btnok;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser jdFecha_actual;
    private javax.swing.JComboBox<String> txtcategoria;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdescuento;
    private javax.swing.JButton txtnuevo;
    private javax.swing.JTextField txtpiezas;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtsub;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txtvendedor;
    // End of variables declaration//GEN-END:variables
}
